language: android

sudo: required

jdk: oraclejdk8

env:
  global:
    - ANDROID_API=26
    - ANDROID_BUILD_TOOLS=26.0.1
    
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API

before_install:
- chmod +x gradlew

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
