language: android

sudo: required

jdk: oraclejdk8

env:
  global:
    - ANDROID_API=19

before_install:
- chmod +x gradlew

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
